version: 2
jobs:
  build:
    docker:
      - image: ishikocpp/gcc-boost:10.1.0-1.73.0
    steps:
      - run: 
          name: "Set ISHIKO_CPP environment variable and create workspace directory"
          command: mkdir -p /projects/ishiko/cpp && echo 'export ISHIKO_CPP="/projects/ishiko/cpp"' >> $BASH_ENV
      - run:
          name: "Install build dependency: Ishiko/C++ Platform"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/platform.git && cd platform/build/gnumake && make
      - checkout:
          path: /projects/ishiko/cpp/text
      - run:
          name: Build
          command: cd /projects/ishiko/cpp/text/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Errors"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/errors.git && cd errors/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Process"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/process.git && cd process/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Diff"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/diff.git && cd diff/core/build/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Test"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/test.git && cd test/core/build/gnumake && make
      - run:
          name: Test build
          command: cd /projects/ishiko/cpp/text/Tests/Makefiles/GNUmakefile && make
      - run:
          name: Run the tests
          command: cd /projects/ishiko/cpp/text/Tests/Makefiles/GNUmakefile && ./IshikoTextTests
